sudo: false
os:
  - linux
language: python
python:
  - 3.5
  - 3.6
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install codecov
script:
  - pytest -rxsX --cov --flake8
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
